# Generated by Django 3.2.8 on 2021-11-26 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
        ('farm_app', '0002_variantcommission_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantcommission',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='variantcommission',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_commission_product', to='product.product'),
        ),
        migrations.AddField(
            model_name='variantcommission',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_Commission_variant', to='product.variant'),
        ),
        migrations.AddField(
            model_name='stagesmaster',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stagesmaster',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_product', to='product.product'),
        ),
        migrations.AddField(
            model_name='farmstagesimage',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farmstagesimage',
            name='farm_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_stage_image', to='farm_app.farmstage'),
        ),
        migrations.AddField(
            model_name='farmstage',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_stage_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farmstage',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_stage', to='farm_app.farms'),
        ),
        migrations.AddField(
            model_name='farmstage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_stage_product', to='product.product'),
        ),
        migrations.AddField(
            model_name='farmstage',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage', to='farm_app.stagesmaster'),
        ),
        migrations.AddField(
            model_name='farmstage',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_stage_variant', to='product.variant'),
        ),
        migrations.AddField(
            model_name='farmsimage',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farmsimage',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_image', to='farm_app.farms'),
        ),
        migrations.AddField(
            model_name='farms',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_category', to='product.category'),
        ),
        migrations.AddField(
            model_name='farms',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farms',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_product', to='product.product'),
        ),
        migrations.AddField(
            model_name='farms',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farms',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_variant', to='product.variant'),
        ),
        migrations.AddField(
            model_name='farmerpayment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_payment_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farmerpayment',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_farm', to='farm_app.farms'),
        ),
        migrations.AddField(
            model_name='farmerpayment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_stage_product', to='product.product'),
        ),
        migrations.AddField(
            model_name='farmerpayment',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_stage', to='farm_app.stagesmaster'),
        ),
        migrations.AddField(
            model_name='farmerpayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farmerpayment',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_stage_variant', to='product.variant'),
        ),
        migrations.AlterUniqueTogether(
            name='stagesmaster',
            unique_together={('stage_no', 'product')},
        ),
    ]
