# Generated by Django 3.2.8 on 2021-11-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmstage',
            name='message',
            field=models.TextField(default='NOT ADDED'),
        ),
    ]
