# Generated by Django 3.2.8 on 2023-06-06 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0005_farmlogs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmlogs',
            options={'ordering': ['-created_on']},
        ),
    ]
