# Generated by Django 3.2.8 on 2021-11-26 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
        ('buyer', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmpurchase',
            name='purchased_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_purchased_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farmpurchase',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_purchase_variant', to='product.variant'),
        ),
    ]
